name: Run Tests

on: [push]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java
      with:
        java-version: 11  

    - name: Build and Run Tests
      run: |
        ./gradlew build  
        ./gradlew test   

    - name: Upload Test Results
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: build/test-results
